version: '3.9'
services:
  backend:
    container_name: portfolio-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - app-network

  frontend:
    container_name: portfolio-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: portfolio-db
    restart: always
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4545
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: portfolio-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
