// 📁 src/constants/iconOptions.jsx
import {
  FaDocker,
  FaReact,
  FaNodeJs,
  FaGithub,
  FaHtml5,
  FaCss3Alt,
  FaGitAlt,
  FaUserTie,
  FaClock,
  FaPaintBrush,
  FaBrain,
  FaJava,
  FaPython,
  FaPhp,
  FaRust,
  FaGem,
  FaCode,
  FaServer,
  FaDatabase,
  FaCogs,
  FaTools,
  FaChartBar,
  FaFileCode,
} from "react-icons/fa";
import {
  SiPostgresql,
  SiTypescript,
  SiJavascript,
  SiTailwindcss,
  SiNestjs,
  SiExpress,
  SiNextdotjs,
  SiMongodb,
  SiPrisma,
  SiRedis,
  SiGraphql,
  SiSocketdotio,
  SiVuedotjs,
  SiDjango,
  SiFlask,
  SiDotnet,
  SiGitlab,
  SiNginx,
  SiAmazon, // Changed from SiAmazonaws to SiAmazon
  SiVercel,
  SiDigitalocean,
  SiJest,
  SiCypress,
  SiWebpack,
  SiBabel,
  SiFigma,
  SiSass,
  SiGo,
  SiCplusplus,
  SiSwagger,
  SiPostman,
  SiStorybook,
  SiSentry,
} from "react-icons/si";
import { GrMysql } from "react-icons/gr";
import { MdRecordVoiceOver, MdGroups } from "react-icons/md";
import { GiPuzzle } from "react-icons/gi";
import { TbBrandVscode } from "react-icons/tb";
import { BsFillGearFill } from "react-icons/bs";
import { AiFillApi } from "react-icons/ai";

// ✅ Icon-based Skills
export const iconOptions = [
  // 🚀 HARD SKILLS
  // Dasturlash tillari
  { label: "JavaScript", value: "SiJavascript", icon: <SiJavascript /> },
  { label: "TypeScript", value: "SiTypescript", icon: <SiTypescript /> },
  { label: "Python", value: "FaPython", icon: <FaPython /> },
  { label: "Java", value: "FaJava", icon: <FaJava /> },
  { label: "C#", value: "SiDotnet", icon: <SiDotnet /> },
  { label: "Go (Golang)", value: "SiGo", icon: <SiGo /> },
  { label: "Rust", value: "FaRust", icon: <FaRust /> },
  { label: "C/C++", value: "SiCplusplus", icon: <SiCplusplus /> },
  { label: "PHP", value: "FaPhp", icon: <FaPhp /> },
  { label: "Ruby", value: "FaGem", icon: <FaGem /> },

  // Frontend texnologiyalari
  { label: "HTML5", value: "FaHtml5", icon: <FaHtml5 /> },
  { label: "CSS3", value: "FaCss3Alt", icon: <FaCss3Alt /> },
  { label: "SCSS/SASS", value: "SiSass", icon: <SiSass /> },
  { label: "TailwindCSS", value: "SiTailwindcss", icon: <SiTailwindcss /> },
  { label: "React.js", value: "FaReact", icon: <FaReact /> },
  { label: "Vue.js", value: "SiVuedotjs", icon: <SiVuedotjs /> },
  { label: "Next.js", value: "SiNextdotjs", icon: <SiNextdotjs /> },
  { label: "GraphQL", value: "SiGraphql", icon: <SiGraphql /> },
  { label: "WebSocket", value: "SiSocketdotio", icon: <SiSocketdotio /> },

  // Backend texnologiyalari
  { label: "Node.js", value: "FaNodeJs", icon: <FaNodeJs /> },
  { label: "Express.js", value: "SiExpress", icon: <SiExpress /> },
  { label: "NestJS", value: "SiNestjs", icon: <SiNestjs /> },
  { label: "Django", value: "SiDjango", icon: <SiDjango /> },
  { label: "Flask", value: "SiFlask", icon: <SiFlask /> },
  { label: "Spring Boot", value: "FaJava", icon: <FaJava /> }, // Spring Boot Java asosida
  { label: ".NET Core", value: "SiDotnet", icon: <SiDotnet /> },

  // Ma'lumotlar bazasi
  { label: "PostgreSQL", value: "SiPostgresql", icon: <SiPostgresql /> },
  { label: "MySQL", value: "GrMysql", icon: <GrMysql /> },
  { label: "MongoDB", value: "SiMongodb", icon: <SiMongodb /> },
  { label: "Redis", value: "SiRedis", icon: <SiRedis /> },
  { label: "Prisma", value: "SiPrisma", icon: <SiPrisma /> },

  // DevOps, Deployment va Infrastructure
  { label: "Git", value: "FaGitAlt", icon: <FaGitAlt /> },
  { label: "GitHub", value: "FaGithub", icon: <FaGithub /> },
  { label: "GitLab", value: "SiGitlab", icon: <SiGitlab /> },
  { label: "Docker", value: "FaDocker", icon: <FaDocker /> },
  { label: "Nginx", value: "SiNginx", icon: <SiNginx /> },
  { label: "AWS", value: "SiAmazon", icon: <SiAmazon /> }, // Changed from SiAmazonaws to SiAmazon
  { label: "Vercel", value: "SiVercel", icon: <SiVercel /> },
  { label: "DigitalOcean", value: "SiDigitalocean", icon: <SiDigitalocean /> },

  // Testing va sifat nazorati
  { label: "Jest", value: "SiJest", icon: <SiJest /> },
  { label: "Cypress", value: "SiCypress", icon: <SiCypress /> },

  // Integratsiyalar va qo‘shimcha vositalar
  { label: "Webpack", value: "SiWebpack", icon: <SiWebpack /> },
  { label: "Babel", value: "SiBabel", icon: <SiBabel /> },
  { label: "Postman", value: "SiPostman", icon: <SiPostman /> },
  { label: "Swagger", value: "SiSwagger", icon: <SiSwagger /> },
  { label: "Storybook", value: "SiStorybook", icon: <SiStorybook /> },
  { label: "Sentry", value: "SiSentry", icon: <SiSentry /> },
  { label: "Figma", value: "SiFigma", icon: <SiFigma /> },

  // 🌱 SOFT SKILLS
  {
    label: "Communication",
    value: "MdRecordVoiceOver",
    icon: <MdRecordVoiceOver />,
  },
  { label: "Teamwork", value: "MdGroups", icon: <MdGroups /> },
  { label: "Critical Thinking", value: "FaBrain", icon: <FaBrain /> },
  { label: "Problem Solving", value: "GiPuzzle", icon: <GiPuzzle /> },
  { label: "Leadership", value: "FaUserTie", icon: <FaUserTie /> },
  { label: "Time Management", value: "FaClock", icon: <FaClock /> },
  { label: "Creativity", value: "FaPaintBrush", icon: <FaPaintBrush /> },

  // 📚 Qo‘shimcha Skillar (umumiy ikonka bilan)
  { label: "Algorithms", value: "FaCode", icon: <FaCode /> },
  { label: "Data Structures", value: "FaDatabase", icon: <FaDatabase /> },
  { label: "API Design", value: "AiFillApi", icon: <AiFillApi /> },
  { label: "Design Patterns", value: "FaCogs", icon: <FaCogs /> },
];

// 📚 Non-icon fallback entries for other skills (no icons)
export const extraSkills = [
  "Rekursiya",
  "BigONotation",
  "OOP",
  "FunctionalProgramming",
  "AsyncProgramming",
  "Multithreading",
  "JavaScriptDOM",
  "ReduxZustandJotai",
  "WebAccessibility",
  "RESTAPI",
  "SQLite",
  "TypeORM",
  "Sequelize",
  "QueryOptimization",
  "Transactions",
  "Indexing",
  "Migrations",
  "UnitTesting",
  "IntegrationTesting",
  "EndToEndTesting",
  "MochaChai",
  "Playwright",
  "Coverage",
  "Mocking",
  "TDD",
  "CICD",
  "PM2",
  "Netlify",
  "LinuxBashScripting",
  "Microservices",
  "MonolithicArchitecture",
  "Serverless",
  "LoadBalancing",
  "RabbitMQ",
  "Kafka",
  "EventDrivenArchitecture",
  "Caching",
  "CAPTheorem",
  "Scalability",
  "AuthenticationAuthorization",
  "Vite",
  "Parcel",
  "Insomnia",
  "StripePayme",
  "TelegramBotAPI",
  "GoogleMapsAPI",
  "SEO",
  "PerformanceOptimization",
  "LogRocket",
  "PrettierESLint",
  "JSDoc",
  "Documentation",
  "CodeReview",
  "Refactoring",
  "GitCommitConvention",
  "EnglishTechnicalReading",
  "PresentationSkills",
  "InterviewPreparation",
  "Mentorship",
  "AgileScrum",
  "ContinuousLearning",
  "SideProjects",
  "OpenSourceContributions",
  "Portfolio",
  "TechnicalBlogging",
  "StackOverflow",
  "CVLinkedIn",
  // Qo‘shimcha skillar
  "Kubernetes",
  "Terraform",
  "Ansible",
  "CloudFormation",
  "GraphDatabases",
  "MachineLearning",
  "DataAnalysis",
  "Blockchain",
  "Web3",
  "CI/CD",
  "Prometheus",
  "Grafana",
  "ELKStack",
  "SecurityBestPractices",
  "PenetrationTesting",
  "CodeOptimization",
  "DesignSystems",
];
